export enum routes {
  DASHBOARD = '/dashboard',
  TYPOGRAPHY = '/typography',
  TABLES = '/users',
  EDIT_USER = '/users/edit',
  GAMES = '/games',
  CREATE_GAMES = '/games/create',
  CATEGORIES = '/categories',
  CREATE_CATEGORY = '/categories/create',
  EDIT_CATEGORY = '/categories/edit',
  PACKAGE = '/package',
  ORDER = '/order',
  BLOG = '/blog',
  CREATE_PACKAGE = '/package/create',
  EDIT_PACKAGE = '/package/edit',
  NOTIFICATION = '/notification',
  UI_ELEMENTS_ICONS = '/ui/icons',
  UI_ELEMENTS_CHARTS = '/ui/charts',
  UI_ELEMENTS_MAP = '/ui/map',
  LOGIN = '/login'
}
