export enum routes {
  DASHBOARD = '/dashboard',
  TYPOGRAPHY = '/typography',
  TABLES = '/users',
  PASSWORD = '/password',
  EDIT_USER = '/users/edit',
  GAMES = '/games',
  CREATE_GAMES = '/games/create',
  EDIT_GAMES = '/games/edit',
  CATEGORIES = '/categories',
  CREATE_CATEGORY = '/categories/create',
  EDIT_CATEGORY = '/categories/edit',
  PACKAGE = '/package',
  ORDER = '/order',
  EDIT_ORDER = '/order/edit',
  BLOG = '/blog',
  CREATE_BLOG = '/blog/create',
  EDIT_BLOG = '/blog/edit',
  CREATE_PACKAGE = '/package/create',
  EDIT_PACKAGE = '/package/edit',
  BANNER = '/banner',
  CREATE_BANNER = '/banner/create',
  NOTIFICATION = '/notification',
  UI_ELEMENTS_ICONS = '/ui/icons',
  UI_ELEMENTS_CHARTS = '/ui/charts',
  UI_ELEMENTS_MAP = '/ui/map',
  LOGIN = '/login'
}
